In [2]:
library(readr)
library(readxl)
library(rcompanion)
library(fastR2)
library(car)

In [3]:
honey <- read_csv("/Users/julieraeboucher/Desktop/Work/Mentorship /Curriculum/3. Datasets/honey.csv")

Rows: 201 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): state
dbl (7): numcol, yieldpercol, totalprod, stocks, priceperlb, prodvalue, year

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

---

### Explore Data

In [4]:
head(honey)

  state numcol yieldpercol totalprod stocks  priceperlb prodvalue year
1 AL      9000 66            594000   214000 1.90        1129000  2008
2 AZ     25000 64           1600000   336000 1.26        2016000  2008
3 AR     28000 75           2100000   525000 1.35        2835000  2008
4 CA    360000 51          18360000  4039000 1.39       25520000  2008
5 CO     27000 45           1215000   656000 1.51        1835000  2008
6 FL    150000 79          11850000  1304000 1.32       15642000  2008

In [5]:
# columns
names(honey)

[1] "state"       "numcol"      "yieldpercol" "totalprod"   "stocks"
[6] "priceperlb"  "prodvalue"   "year"

In [9]:
# shape and data types
# 201 rows / 8 columns
str(honey)

spc_tbl_ [201 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ state      : chr [1:201] "AL" "AZ" "AR" "CA" ...
 $ numcol     : num [1:201] 9000 25000 28000 360000 27000 150000 65000 10000 90000 8000 ...
 $ yieldpercol: num [1:201] 66 64 75 51 45 79 71 90 40 56 ...
 $ totalprod  : num [1:201] 594000 1600000 2100000 18360000 1215000 ...
 $ stocks     : num [1:201] 214000 336000 525000 4039000 656000 ...
 $ priceperlb : num [1:201] 1.9 1.26 1.35 1.39 1.51 1.32 1.52 1.59 1.46 2.59 ...
 $ prodvalue  : num [1:201] 1129000 2016000 2835000 25520000 1835000 ...
 $ year       : num [1:201] 2008 2008 2008 2008 2008 ...
 - attr(*, "spec")=
  .. cols(
  ..   state = col_character(),
  ..   numcol = col_double(),
  ..   yieldpercol = col_double(),
  ..   totalprod = col_double(),
  ..   stocks = col_double(),
  ..   priceperlb = col_double(),
  ..   prodvalue = col_double(),
  ..   year = col_double()
  .. )
 - attr(*, "problems")=<externalptr>

In [11]:
# look if there is any missing data
honey %>% summarise_all(funs(sum(is.na(.))))

Warning message:
“`funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))”

  state numcol yieldpercol totalprod stocks priceperlb prodvalue year
1 0     0      0           0         0      0          0         0

---

### Data Wrangling¶
- remove missing data (NaRV.omit() or subset)
- remove any duplicates

There is no missing data or duplicates we can move on to the Question


---

### Question Setup

You will determine whether honey production `totalprod` has changed over the years, `year` ,using a repeated measures ANOVA. Provide a one-sentence conclusion at the bottom of your program file about the analysis you performed.

```
Notes:
Repeated Measures ANOVAs, also known as within subjects ANOVAs, are when you are measuring the same person or thing repeatedly over time. Although they are used extensively in research studies and experiments, they often have in real-world data science applications when looking at changes over time. For instance, did unemployment rate increase from 2008 to 2009?

As with all ANOVAs, the IV will be categorical, and the DV will be continuous.
```

- DV: year
- IV: totalprod

---

In [12]:
unique(honey$year)

[1] 2008 2009 2010 2011 2012

In [13]:
unique(honey$totalprod)

  [1]   594000  1600000  2100000 18360000  1215000 11850000  4615000   900000
  [9]  3600000   448000   469000  1488000   610000   156000  3080000   294000
 [17]  5183000  9516000  1372000   583000  9380000  2412000   290000   360000
 [25]   288000  3500000   624000 36000000   742000  2150000  1104000 21375000
 [33]   427000  4928000  1344000   330000   252000  2156000   258000  4640000
 [41]  2379000   450000  1040000  1368000 11715000  1484000 11560000  2665000
 [49]   950000  4738000   272000  1092000   567000   175000  3811000   300000
 [57]  3960000  7930000  1456000   517000 10220000  2688000   352000   420000
 [65]  2925000   495000 34650000   550000  1870000   840000 17820000   357000
 [73]  5607000   988000   245000   234000  2728000   185000  3780000  1776000
 [81]   486000  1848000  1500000 27470000  1904000 13800000  2530000   770000
 [89]  2619000   369000   430000  1323000   468000   335000  2880000   205000
 [97]  4118000  8448000  1568000   572000 11618000  2255000   455000   462000
[105]   598000 46410000  1116000  2301000  1110000 15370000   504000  7200000
[113]   780000   260000  2627000   200000  4096000  1224000  1219000  1408000
[121] 17760000  1705000 10980000  2795000   666000  3132000   350000   408000
[129]  1550000   308000  2772000   120000  4736000  6360000  2070000   344000
[137] 13340000  2419000   451000   392000  2744000   868000 32660000   990000
[145]  2040000  1056000 16500000  4524000   897000   172000   160000  2698000
[153]   212000  3591000  1890000   432000  1012000  1575000 11550000  1200000
[161] 12352000  3009000   750000  2944000   472000  2257000   255000  3526000
[169]   136000  4161000  8375000  2124000   371000  7540000  2601000   507000
[177] 33120000  1080000  1920000   960000 16380000   366000  4784000   240000
[185]   164000  2542000  4140000  2550000